Zo
cfulks73/cards pull request #6
Opened 2021-11-12 04:22 UTC by zshrestha2

2021-11-12 04:36 UTC, cfulks73 commented
Don't merge - Blocked by #5 so we can avoid future headaches with cached files causing and it'll also make reviewing the PR easier.

2021-11-12 15:38 UTC, Murazor-byte approved these changes

2021-11-13 18:24 UTC, cfulks73 requested changes
I have a few small changes.

Also, the solitaire.cs file name should be capitalized as well.

2021-11-13 18:24 UTC, cfulks73 commented on Card.cs
> +    public int value;
Class fields should be private w/ getters (don't add setters since the class should be immutable)

2021-11-13 18:24 UTC, cfulks73 commented on solitaire.cs
> +    public class solitaire
Class names should be capitalized

2021-11-13 18:24 UTC, cfulks73 commented on solitaire.cs
> +        private bool validSuitMove()
C# Method names are PascalCase (capitalize all the words).

2021-11-16 02:18 UTC, jackelyny approved these changes

2021-11-19 18:08 UTC, closed without merging